#!/bin/sh

CROSS_COMPILE=arm-linux-gnueabihf-
CC=arm-linux-gnueabihf-gcc
ccache -V &> /dev/null
if [ $? -eq 0 ]; then 
	CC="ccache ${CC}"
fi

make clean
./configure BananaPi
make CROSS_COMPILE="${CROSS_COMPILE}" CC="${CC}"
